flowchart TD
codemyspeccli_terminalpanes[CodeMySpecCli.TerminalPanes]
codemyspec_contentadmin[CodeMySpec.ContentAdmin]
codemyspec_github[CodeMySpec.GitHub]
codemyspeccli_hooks[CodeMySpecCli.Hooks]
codemyspecweb_oauthcontroller[CodeMySpecWeb.OAuthController]
codemyspec_environments[CodeMySpec.Environments]
codemyspec_tests[CodeMySpec.Tests]
codemyspec_stories[CodeMySpec.Stories]
codemyspec_mcpservers[CodeMySpec.McpServers]
codemyspec[CodeMySpec]
codemyspecweb_gettext[CodeMySpecWeb.Gettext]
codemyspec_acceptancecriteria[CodeMySpec.AcceptanceCriteria]
codemyspec_bogus[CodeMySpec.Bogus]
codemyspecweb_telemetry[CodeMySpecWeb.Telemetry]
codemyspec_release[CodeMySpec.Release]
codemyspecweb_usersocket[CodeMySpecWeb.UserSocket]
codemyspecweb_endpoint[CodeMySpecWeb.Endpoint]
codemyspec_integrations[CodeMySpec.Integrations]
codemyspec_localserver[CodeMySpec.LocalServer]
codemyspec_projectsetupwizard[CodeMySpec.ProjectSetupWizard]
codemyspec_bddspecs[CodeMySpec.BddSpecs]
codemyspecweb_contentsynccontroller[CodeMySpecWeb.ContentSyncController]
codemyspec_validation[CodeMySpec.Validation]
codemyspec_rules[CodeMySpec.Rules]
codemyspec_projects[CodeMySpec.Projects]
codemyspecweb_projectcontroller[CodeMySpecWeb.ProjectController]
codemyspecweb_usercontroller[CodeMySpecWeb.UserController]
codemyspec_application[CodeMySpec.Application]
codemyspec_projectcoordinator[CodeMySpec.ProjectCoordinator]
codemyspec_vault[CodeMySpec.Vault]
codemyspec_staticanalysis[CodeMySpec.StaticAnalysis]
codemyspec_content[CodeMySpec.Content]
codemyspecweb_pagehtml[CodeMySpecWeb.PageHTML]
codemyspecweb_typeaheadcomponent[CodeMySpecWeb.TypeaheadComponent]
codemyspec_code[CodeMySpec.Code]
codemyspec_clientusers[CodeMySpec.ClientUsers]
metricflowweb_dashboardlive[MetricFlowWeb.DashboardLive]
codemyspecweb_errorhtml[CodeMySpecWeb.ErrorHTML]
codemyspecweb_presence[CodeMySpecWeb.Presence]
codemyspecweb_integrationscontroller[CodeMySpecWeb.IntegrationsController]
codemyspecweb_storiesjson[CodeMySpecWeb.StoriesJSON]
codemyspec_documents[CodeMySpec.Documents]
codemyspec_tags[CodeMySpec.Tags]
codemyspec_utils[CodeMySpec.Utils]
codemyspecweb_projectcoordinatorjson[CodeMySpecWeb.ProjectCoordinatorJSON]
codemyspecweb_oauthhtml[CodeMySpecWeb.OAuthHTML]
codemyspecweb_router[CodeMySpecWeb.Router]
codemyspecweb[CodeMySpecWeb]
codemyspec_architecture[CodeMySpec.Architecture]
codemyspec_mailer[CodeMySpec.Mailer]
codemyspec_invitations[CodeMySpec.Invitations]
codemyspec_userpreferences[CodeMySpec.UserPreferences]
codemyspecweb_changesetjson[CodeMySpecWeb.ChangesetJSON]
codemyspecweb_sessionchannel[CodeMySpecWeb.SessionChannel]
codemyspec_authorization[CodeMySpec.Authorization]
codemyspecweb_usersessioncontroller[CodeMySpecWeb.UserSessionController]
codemyspec_repo[CodeMySpec.Repo]
codemyspec_users[CodeMySpec.Users]
codemyspec_quality[CodeMySpec.Quality]
codemyspec_compile[CodeMySpec.Compile]
codemyspecweb_storiescontroller[CodeMySpecWeb.StoriesController]
codemyspecweb_projectcoordinatorcontroller[CodeMySpecWeb.ProjectCoordinatorController]
codemyspec_problems[CodeMySpec.Problems]
codemyspecweb_pagecontroller[CodeMySpecWeb.PageController]
structintrospector[StructIntrospector]
metricflow_dashboards[MetricFlow.Dashboards]
sessions_session[Sessions.Session]
codemyspecweb_errorjson[CodeMySpecWeb.ErrorJSON]
codemyspec_accounts[CodeMySpec.Accounts]
sessions_sessionstack[Sessions.SessionStack]
codemyspec_projectsync[CodeMySpec.ProjectSync]
codemyspec_components[CodeMySpec.Components]
codemyspec_fileedits[CodeMySpec.FileEdits]
codemyspec_requirements[CodeMySpec.Requirements]
codemyspec_transcripts[CodeMySpec.Transcripts]
codemyspecweb_fallbackcontroller[CodeMySpecWeb.FallbackController]
sessions_sessiontype[Sessions.SessionType]
codemyspecweb_corecomponents[CodeMySpecWeb.CoreComponents]
codemyspec_git[CodeMySpec.Git]
codemyspecweb_layouts[CodeMySpecWeb.Layouts]
codemyspec_sessions[CodeMySpec.Sessions]
codemyspecweb_userauth[CodeMySpecWeb.UserAuth]
codemyspec_contentsync[CodeMySpec.ContentSync]
testappweb_dashboardlive[TestAppWeb.DashboardLive]
codemyspec_agenttasks[CodeMySpec.AgentTasks]
codemyspec_agenttasks --> codemyspec_utils
codemyspec_agenttasks --> codemyspec_components
codemyspec_agenttasks --> codemyspec_requirements
codemyspec_agenttasks --> codemyspec_rules
codemyspec_mcpservers --> codemyspec_acceptancecriteria
codemyspec_mcpservers --> codemyspec_stories
codemyspec_quality --> codemyspec_tests
codemyspec_stories --> codemyspec_acceptancecriteria
codemyspec_stories --> codemyspec_users
codemyspec_staticanalysis --> codemyspec_users
codemyspec_staticanalysis --> codemyspec_problems
codemyspec_staticanalysis --> codemyspec_projects
codemyspec_mcpservers --> codemyspec_sessions
codemyspec_mcpservers --> codemyspec_components
codemyspec_requirements --> codemyspec_components
codemyspec_requirements --> codemyspec_users
codemyspec_accounts --> codemyspec_users
codemyspec_components --> codemyspec_repo
codemyspec_components --> codemyspec_users
codemyspeccli_hooks --> codemyspec_sessions
codemyspec_acceptancecriteria --> codemyspec_users
codemyspec_acceptancecriteria --> codemyspec_stories
codemyspec_bddspecs --> codemyspec_acceptancecriteria
codemyspec_bddspecs --> codemyspec_stories
codemyspec_requirements --> codemyspec_utils
codemyspec_architecture --> codemyspec_components
codemyspec_requirements --> codemyspec_environments
codemyspec_accounts --> codemyspec_repo
codemyspec_requirements --> codemyspec_documents
codemyspec_bddspecs --> codemyspec_users
codemyspec_validation --> codemyspec_transcripts
codemyspec_validation --> codemyspec_problems
codemyspec_validation --> codemyspec_projectsync
codemyspec_validation --> codemyspec_utils
codemyspec_validation --> codemyspec_sessions
codemyspec_validation --> codemyspec_components
codemyspec_content --> codemyspec_repo
codemyspec_agenttasks --> codemyspec_environments
codemyspec_contentadmin --> codemyspec_repo
codemyspec_contentadmin --> codemyspec_users
codemyspec_sessions --> codemyspec_environments
codemyspec_agenttasks --> codemyspec_bddspecs
codemyspec_git --> codemyspec_integrations
codemyspec_git --> codemyspec_users
codemyspec_agenttasks --> codemyspec_stories
codemyspec_problems --> codemyspec_projects
codemyspec_acceptancecriteria --> codemyspec_repo
codemyspec_contentsync --> codemyspec_users
codemyspec_tags --> codemyspec_users
codemyspec_tags --> codemyspec_stories
codemyspec_mcpservers --> codemyspec_environments
codemyspec_agenttasks --> codemyspec_documents
codemyspec_requirements --> codemyspec_sessions
codemyspec_architecture --> codemyspec_documents
codemyspec_architecture --> codemyspec_environments
codemyspec_architecture --> codemyspec_stories
codemyspec_staticanalysis --> codemyspec_documents
codemyspec_staticanalysis --> codemyspec_code
codemyspec_staticanalysis --> codemyspec_utils
codemyspec_architecture --> codemyspec_users
codemyspec_stories --> codemyspec_components
codemyspec_quality --> codemyspec_utils
codemyspec_quality --> codemyspec_components
codemyspec_quality --> codemyspec_code
codemyspec_contentsync --> codemyspec_git
codemyspec_contentsync --> codemyspec_projects
codemyspec_bddspecs --> codemyspec_code
codemyspec_mcpservers --> codemyspec_repo
codemyspec_requirements --> codemyspec_repo
codemyspec_stories --> codemyspec_repo
codemyspec_stories --> codemyspec_projects
codemyspec_stories --> codemyspec_accounts
codemyspec_tests --> codemyspec_problems
codemyspec_accounts --> codemyspec_authorization
codemyspec_content --> codemyspec_users
codemyspec_components --> codemyspec_requirements
codemyspec_agenttasks --> codemyspec_problems